---
title: "LogisticRegressionModel"
author: "Sam Milnes"
date: "4/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

pga <- read.csv("2022Masters_pred_data.csv")

# Get rid of first column
pga <- pga[, -1]

# Get rid of x_attempts and hole proximity columns
pga <- subset(pga, select = -c(hole_proximity, x_of_attempts))

# Get rid of "T" in masters finish and ranking columns
pga$masters_finish<-gsub("T","",as.character(pga$masters_finish))
pga$ranking<-gsub("T","",as.character(pga$ranking))



# Converting distance columns to inches

pga_mat_fair <- stringr::str_extract_all(pga$prox_fair, "\\d+", simplify = TRUE)
pga$prox_fair <- as.numeric(pga_mat_fair[, 1]) * 12 + as.numeric(pga_mat_fair[, 2])
pga_mat_rough <- stringr::str_extract_all(pga$prox_rough, "\\d+", simplify = TRUE)
pga$prox_rough <- as.numeric(pga_mat_rough[, 1]) * 12 + as.numeric(pga_mat_rough[, 2])
pga_mat_arg <- stringr::str_extract_all(pga$prox_arg, "\\d+", simplify = TRUE)
pga$prox_arg <- as.numeric(pga_mat_arg[, 1]) * 12 + as.numeric(pga_mat_arg[, 2])


# Fill in NA's for score_average column to median
#pga$score_average[is.na(pga$score_average)] <- median(pga$score_average, na.rm = T)


# Get rid of all rows that have "CU" for masters finish column. This indicates
# That the player did not make the cut, if kept in, this would skew the total score column
newPGA <- subset(pga, (pga$masters_finish != "CU"))
newPGA2 <- subset(newPGA, newPGA$masters_finish != "WD")                 


# Change the value in the masters finish column to 1 if "Win"
newPGA2$masters_finish[newPGA2$masters_finish == "Win"] <- 1 

#Get rid of NA's
newPGA2 <- na.omit(newPGA2)
testData2021 <- newPGA2
testData2021 <- testData2021[which(testData2021$year == 2021),]
testData2021$masters_finish <- as.numeric(as.character(testData2021$masters_finish))
testData2021$masters_top_10 <- ifelse(testData2021$masters_finish < 11, 1, 0)

# Drop player name column
newPGA2 <- newPGA2[, -2]


# Cleaned Data-frame to use for testing
#View(newPGA2)

```


```{r}
#Splitting data in training and test data

# Getting all data before 2021 season
data.train <- newPGA2[which(newPGA2$year < 2021),]
data.train$ranking <- as.numeric(as.character(data.train$ranking))
data.test$ranking <- as.numeric(as.character(data.test$ranking))
newPGA2$ranking <- as.numeric(as.character(newPGA2$ranking))
#data.train$masters_finish <- as.numeric(as.character(data.train$masters_finish))
#data.train <- subset(data.train, select = -c(masters_finish))
data.train <- data.train[, -1]




# Getting all data from the 2021 season.
data.test <- newPGA2[which(newPGA2$year == 2021),]

```




```{r}

#Adding column
#1 if the golfer finished in the top 10 
#0 if outside the top 10

newPGA2$masters_finish <- as.numeric(as.character(newPGA2$masters_finish))

newPGA2$masters_top_10 <- ifelse(newPGA2$masters_finish < 11, 1, 0)


data.train$masters_finish <- as.numeric(as.character(data.train$masters_finish))

data.train$masters_top_10 <- ifelse(data.train$masters_finish < 11, 1, 0)






```

```{r}
# masters.logisticReg <- glm(masters_top_10 ~ driving_distance + sg_putt + ranking + rounds + gir + top_10 + putts_round, 
#                            data = data.train, family = binomial)

masters.logisticReg2 <- glm(masters_top_10 ~ driving_distance + sg_putt + rounds + gir + putts_round, 
                           data = data.train, family = binomial)

# summary(masters.logisticReg)
summary(masters.logisticReg2)

cor(data.train)

```

```{r}
# newPGA2 <- subset(newPGA2, select = -c(masters_top_10))


myprobability2 <- predict(masters.logisticReg2, data.test, type = "response")

myprobability2



prediction.logistic2 <- rep(0, length(newlogisticprediction))

# masters.logisticReg2[newlogisticprediction > 0.5] <- 1
# table(newlogisticprediction, newPGA2$masters_top_10)



# logisticPrediction <- predict(masters.logisticReg2, data.test, type = "response")

prediction.logistic2[myprobability2 > 0.5] <- 1
table(prediction.logistic2, data.test$masters_top_10)

mean(prediction.logistic2 != data.test$masters_top_10)
testData2021$top_10_prob <- myprobability2

FinalTestDataSub <- subset(testData2021, select =  c(year, player_name, total_score,
                                            masters_top_10, top_10_prob))



```

```{r}
#View(testData2021)
testData2021 <- testData2021[which(testData2021$year == 2021),]
testData2021$masters_finish <- sapply(testData2021$masters_finish, as.numeric)
testData2021$masters_top_10 <- ifelse(testData2021$masters_finish < 11, 1, 0)
#View(testData2021)
# Actual top 10
top10 <- testData2021[which(testData2021$masters_top_10 == 1),]
top10
top10Final <- subset(top10, select = c(player_name, masters_finish, total_score))
top10Final
View(top10Final)
top10Finishers <- subset(top10, select = c(player_name, masters_finish, total_score))
top10Finishers
```






